###
### Workflow that lints code in pull requests
###

name: Lint

# Note: No name so it uses the name associated with the pull request merge to main

on:
  pull_request:
    paths:
    - 'pivotal-import/**'

jobs:
  lint-pivotal-import:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python &gt;=3.10
        uses: actions/setup-python@v4
        with:
          python-version: "&gt;=3.10"
          cache: "pipenv"

      - name: Install pipenv
        run: pip install --user pipenv

      - name: Install Python dependencies
        working-directory: ./pivotal-import
        run: make setup-dev

      - name: Lint pivotal-import with Black linter
        working-directory: ./pivotal-import
        run: make lint
